import { openaiResponses } from '@inngest/ai/models';
import { inngest } from '../client';
import { adminChannel } from '../channels';
import {
  deterministicReview,
  importInventoryRows,
  parseInventoryDocument,
  type InventoryImportReview,
} from '@/lib/inventory-import';
import { PRODUCTS } from '@/lib/catalog';

const REVIEW_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['ok', 'summary', 'issues', 'missingVariants'],
  properties: {
    ok: { type: 'boolean' },
    summary: { type: 'string' },
    issues: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['severity', 'message', 'row'],
        properties: {
          severity: { type: 'string', enum: ['info', 'warning', 'error'] },
          message: { type: 'string' },
          row: { type: ['number', 'null'] },
        },
      },
    },
    missingVariants: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['product', 'size', 'color'],
        properties: {
          product: { type: 'string' },
          size: { type: ['string', 'null'] },
          color: { type: ['string', 'null'] },
        },
      },
    },
  },
};

export const importInventoryDocument = inngest.createFunction(
  {
    id: 'import-inventory-document',
    name: 'Import Inventory Document',
    retries: 2,
    concurrency: 1,
    triggers: [{ event: 'admin/inventory.document_import.requested' }],
  },
  async ({ event, step }) => {
    const data = event.data as {
      actorEmail?: string;
      sourceName?: string;
      contentType?: string;
      documentText?: string;
    };

    await step.realtime.publish('emit-document-import-running', adminChannel.import, {
      status: 'running',
      message: `Reviewing ${data.sourceName ?? 'inventory document'}`,
      ts: Date.now(),
    });

    try {
      const parsedRows = await step.run('parse-inventory-document', async () => {
        return parseInventoryDocument(data.documentText ?? '');
      });

      const deterministic = deterministicReview(parsedRows);
      const llmReview = await reviewInventoryWithLlm({
        step,
        parsedRows,
        deterministic,
        sourceName: data.sourceName ?? 'uploaded inventory',
        contentType: data.contentType ?? 'text/plain',
      });

      const result = await step.run('apply-reviewed-inventory', async () => {
        return importInventoryRows({
          actorEmail: data.actorEmail ?? '',
          source: `document:${data.sourceName ?? 'uploaded-inventory'}`,
          rows: parsedRows,
          review: llmReview,
        });
      });

      await step.realtime.publish('emit-document-import-complete', adminChannel.import, {
        importRunId: result.importRunId,
        status: 'complete',
        message: `Imported ${result.variants} variants from ${data.sourceName ?? 'document'}`,
        ts: Date.now(),
      });

      await step.sendEvent('check-low-stock-after-document-import', {
        id: `inventory-changed-document-import-${result.importRunId}`,
        name: 'store/inventory.changed',
        data: {
          source: 'inventory-document-import',
          reason: `Inventory document import completed: ${data.sourceName ?? 'document'}`,
          importRunId: result.importRunId,
          actorEmail: data.actorEmail ?? '',
        },
      });

      return { ...result, review: llmReview };
    } catch (err) {
      await step.realtime.publish('emit-document-import-failed', adminChannel.import, {
        status: 'failed',
        message: err instanceof Error ? err.message : String(err),
        ts: Date.now(),
      });
      throw err;
    }
  },
);

async function reviewInventoryWithLlm({
  step,
  parsedRows,
  deterministic,
  sourceName,
  contentType,
}: {
  // The concrete step type is generated by Inngest middleware and is noisy to
  // thread through this small helper; the call site is still typed by SDK use.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  step: any;
  parsedRows: Array<Record<string, string>>;
  deterministic: InventoryImportReview;
  sourceName: string;
  contentType: string;
}): Promise<InventoryImportReview> {
  if (!process.env.OPENAI_API_KEY) {
    return {
      ...deterministic,
      issues: [
        ...deterministic.issues,
        {
          severity: 'warning',
          message: 'LLM review skipped because OPENAI_API_KEY is not configured.',
        },
      ],
    };
  }

  const response = await step.ai.infer('llm-review-inventory-import', {
    model: openaiResponses({ model: process.env.INVENTORY_IMPORT_MODEL ?? 'gpt-4.1-mini' }),
    body: {
      input: JSON.stringify({
        sourceName,
        contentType,
        expectedCatalog: expectedCatalogForReview(),
        parsedRows,
        deterministicReview: deterministic,
      }),
      instructions:
        'You are validating an Inngest swag-store inventory import before it mutates production stock. Check whether every required product and size is represented, quantities are numeric non-negative counts, product names/SKUs are recognizable, and no event-only or do-not-touch inventory is mixed into the upload. Return JSON only. Use severity "error" for anything that should block import.',
      text: {
        format: {
          type: 'json_schema',
          name: 'inventory_import_review',
          strict: true,
          schema: REVIEW_SCHEMA,
        },
      },
      max_output_tokens: 1200,
    },
  });

  return parseLlmReview(response, deterministic);
}

function expectedCatalogForReview() {
  return PRODUCTS.map((product) => {
    const requiredSizes = Array.from(
      new Set(product.variants.flatMap((variant) => (variant.size ? [variant.size] : []))),
    );

    return {
      product: product.name,
      sku: product.sku,
      requiredSizes: requiredSizes.length > 0 ? requiredSizes : ['ONE_SIZE'],
    };
  });
}

function parseLlmReview(response: unknown, fallback: InventoryImportReview): InventoryImportReview {
  try {
    const text = extractOutputText(response);
    const parsed = JSON.parse(text) as InventoryImportReview;
    return {
      ok: Boolean(parsed.ok),
      summary: String(parsed.summary ?? fallback.summary),
      issues: Array.isArray(parsed.issues) ? parsed.issues.map(normalizeIssue) : fallback.issues,
      missingVariants: Array.isArray(parsed.missingVariants)
        ? parsed.missingVariants.map((variant) => ({
            product: String(variant.product ?? ''),
            size: variant.size ? String(variant.size) : undefined,
            color: variant.color ? String(variant.color) : undefined,
          }))
        : fallback.missingVariants,
    };
  } catch (err) {
    return {
      ...fallback,
      issues: [
        ...fallback.issues,
        {
          severity: 'warning',
          message: `LLM review could not be parsed: ${err instanceof Error ? err.message : String(err)}`,
        },
      ],
    };
  }
}

function normalizeIssue(issue: InventoryImportReview['issues'][number]): InventoryImportReview['issues'][number] {
  const severity = issue.severity === 'info' || issue.severity === 'warning' || issue.severity === 'error'
    ? issue.severity
    : 'warning';
  return {
    severity,
    message: String(issue.message ?? ''),
    ...(typeof issue.row === 'number' ? { row: issue.row } : {}),
  };
}

function extractOutputText(response: unknown): string {
  const output = (response as { output?: Array<{ content?: Array<{ type?: string; text?: string }> }> }).output ?? [];
  const text = output
    .flatMap((item) => item.content ?? [])
    .filter((part) => part.type === 'output_text' && part.text)
    .map((part) => part.text)
    .join('\n')
    .trim();

  if (!text) throw new Error('empty model response');
  return text;
}
